// manuscript_data.js
// Textual content from all manuscripts, transformed from TEI XML.

const teiData = {
  "manuscripts": {
    "Q-969": { "idno": "Q-969", "repository": "National Centre of Manuscripts, Georgia", "publication": "Kr. Šarašiʒe, Samxret Sakartvelos isṭoriis masalebi (XV-XVI ss.), Tbilisi 1961, p. 15ff." },
    "Q-642": { "idno": "Q-642", "repository": "National Centre of Manuscripts, Georgia", "publication": "Kr. Šarašiʒe, Samxret Sakartvelos isṭoriis masalebi (XV-XVI ss.), Tbilisi 1961, pp. 21-23." }
  },
  "entries": [
    // --- Entries from Q-969 ---
    { "id": "q969_entry_1", "manuscript": "Q-969", "n": "1", "georgian": { "text": "ბაგრატ აფხაზთა და ქართუჱლთა მართლმადიდებლისა მეფისა საუკუნოჲმცა არს საჴსენებელი.", "markup": [{ "start": 0, "end": 6, "type": "persName", "ref": "p1001" }] }, "english": { "text": "For Bagrat, orthodox king of the Abkhazians and Kartvelians, may his memory be eternal." }, "prosopography": [{ "ref": "p1001", "role": "main" }] },
    { "id": "q969_entry_2", "manuscript": "Q-969", "n": "2", "georgian": { "text": "გიორგი კესაროსისა, აფხაზთაჲ, ქართველთა მეფისა ...", "markup": [{ "start": 0, "end": 6, "type": "persName", "ref": "p1002" }] }, "english": { "text": "Of Giorgi the Caesar, of the Abkhazians, King of the Kartvelians..." }, "prosopography": [{ "ref": "p1002", "role": "main" }] },
    { "id": "q969_entry_3", "manuscript": "Q-969", "n": "3", "georgian": { "text": "დავით ყოვლისა აღმოსავლეთისა მეფისა, ახლისა მართლმადიდებელისა საუკუნოჲმცა საჴსენებელი და კურთხევა მისი.", "markup": [{ "start": 0, "end": 5, "type": "persName", "ref": "p1003" }] }, "english": { "text": "Of Davit, king of all the East, the new orthodox one, may his memory and blessing be eternal." }, "prosopography": [{ "ref": "p1003", "role": "main" }] },
    { "id": "q969_entry_4", "manuscript": "Q-969", "n": "4", "georgian": { "text": "დემეტრე ყოვლისა აღმოსავლეთისა მეფისა საუკუნოჲმცა საჴსენებელი და კურთხევაჲ მისი.", "markup": [{ "start": 0, "end": 7, "type": "persName", "ref": "p1004" }] }, "english": { "text": "Of Demetre, king of all the East, may his memory and blessing be eternal." }, "prosopography": [{ "ref": "p1004", "role": "main" }] },
    { "id": "q969_entry_5", "manuscript": "Q-969", "n": "5", "georgian": { "text": "გიორგი, ყოვლისა აღმოსავლეთისა ჴელმწიფედ მპყრობელისა, მეფეთ-მეფისა საუკუნოჲმცა არს საჴსენებელი და კურთხევაჲ მისი.", "markup": [{ "start": 0, "end": 6, "type": "persName", "ref": "p1005" }] }, "english": { "text": "Of Giorgi, ruler of all the East, King of Kings, may his memory and blessing be eternal." }, "prosopography": [{ "ref": "p1005", "role": "main" }] },
    { "id": "q969_entry_6", "manuscript": "Q-969", "n": "6", "georgian": { "text": "თამარ ყოვლისა აღმოსავლეთისა ახლისა მართლმადიდებლისა, აფხაზთა, ქართველთაჲ, ჰერთა და კახთა და ყოველთა ქრისტეანეთა მპყრობელისა საუკუნოჲმცა არს საჴსენებელი და კურთხევაჲ მისი.", "markup": [{ "start": 0, "end": 5, "type": "persName", "ref": "p1006" }] }, "english": { "text": "Of Tamar, new orthodox one of all the East, ruler of the Abkhazians, Kartvelians, Heretians, and Kakhetians, and all Christians, may her memory and blessing be eternal." }, "prosopography": [{ "ref": "p1006", "role": "main" }] },
    { "id": "q969_entry_7", "manuscript": "Q-969", "n": "7", "georgian": { "text": "ძისა მათისა გიორგი ყოვლისა აღმოსავლეთისა და დასავლეთისა მტკიცედ მპყრობლისა მეფეთ-მეფისა მრავალმცა არიან წელნი მეფობისა მისისანი ...", "markup": [{ "start": 13, "end": 19, "type": "persName", "ref": "p1007" }] }, "english": { "text": "Of their son, Giorgi, firm ruler of all the East and West, King of Kings, may the years of his reign be many..." }, "prosopography": [{ "ref": "p1007", "role": "kinship" }] },
    { "id": "q969_entry_8", "manuscript": "Q-969", "n": "8", "georgian": { "text": "დიდისა და წარჩინებულისა და სიმხნით განთქმულისა და სახელოვანისა და მტერთაგან უძლეველისა ათაბაგ-ამირსპალარისა, მორწმუნისა პატრონისა ჩუენისა ყუარყუარესი საუკუნომცა არს საჴსენებელი და კურთხევა მისი.", "markup": [{ "start": 139, "end": 151, "type": "persName", "ref": "p1008" }] }, "english": { "text": "Of our patron, the great, distinguished, renowned for bravery, glorious and invincible by enemies, Atabag-Amirspasalar, the believer Qvarqvare, may his memory and blessing be eternal." }, "prosopography": [{ "ref": "p1008", "role": "main" }] },
    { "id": "q969_entry_9", "manuscript": "Q-969", "n": "9", "georgian": { "text": "ეგრეთვე მეუღლისა მათისა, დედათა დიდებისა და სიკეთისა ძეგლისა, წმიდათა მენელსაცხებლეთა მოდასისა და სარწმუნოებისა ბეჭედსა და კეთილად მოღუაწისა, ღმრთისმოყუარისა პატრონის დედისიმედის საუკუნოჲცა არს საჴსენებელი და კურთხევაჲ.", "markup": [{ "start": 169, "end": 180, "type": "persName", "ref": "p1009" }] }, "english": { "text": "Likewise, of his wife, the glory of women and monument of goodness, peer of the holy Myrrhbearers, seal of faith and good ascetic, the God-loving patron Dedisimedi, may her memory and blessing also be eternal." }, "prosopography": [{ "ref": "p1009", "role": "wife" }] },
    { "id": "q969_entry_10", "manuscript": "Q-969", "n": "10", "georgian": { "text": "და პირმშოსა ძისა მათისა, სიმჴნით ქებულისა და სიბრძნის გამომეძიებელისა და დაუცხრომელად ღმრთის მადიდებელისა პატრონის ქაიხოსროს საუკუნოჲმცა არს საჴსენებელი და კურთხევაჲ მისი.", "markup": [{ "start": 126, "end": 135, "type": "persName", "ref": "p1010" }] }, "english": { "text": "And of their firstborn son, praised for bravery, seeker of wisdom, and tireless glorifier of God, the patron Kaikhosro, may his memory and blessing be eternal." }, "prosopography": [{ "ref": "p1010", "role": "son" }] },
    { "id": "q969_entry_11", "manuscript": "Q-969", "n": "11", "georgian": { "text": "და შემდგომისა და საყუარელისა ძმისა მისისა, ღმრთივ განბრძნობილისა, მჴნედ მჴედრისა და მრავალთა და ძლიერთა და სახელდებულთა ფალავანთა დამამჴობელისა და ქედისა შემმუსრველისა, საქრისტიანოსა ზღუდისა, სრულისა ჩოხოსნობისა და ანგელოზებრივისა სქემისა ღირსად მიმღებელისა პატრონისა ჩუენისა მზეჭაბუკ-ყოფილსა იაკობისი საუკუნოჲმცა არს საჴსენებელი და კურთხევაჲ მისი.", "markup": [{ "start": 255, "end": 281, "type": "persName", "ref": "p1011" }] }, "english": { "text": "And of his next and beloved brother, made wise by God, a valiant rider and overthrower and neck-crusher of many strong and famous champions, a fence for Christianity, worthy recipient of the full monastic habit and the angelic schema, our patron Mzechabuk, formerly Iakob, may his memory and blessing be eternal." }, "prosopography": [{ "ref": "p1011", "role": "kinship" }] },
    { "id": "q969_entry_12", "manuscript": "Q-969", "n": "12", "georgian": { "text": "და ძმისწულისა მათისა, მჴნისა და ახოვანისა და ქველ-პირმეტყუჱლისა, აგარიანთა მომსრველისა, გულოვნებით სახელგანთქმულისა, მტერთა შემაძრწუნებელისა, სარწმუნოებისა და ქრისტეს ჭეშმარიტისა სჯულისა მტკიცედ მპყრობელისა და აწ მფლობელისა ჩუენისა პატრონისა ნავ (!) ყუარყუარესი საუკუნოჲმცაჲ არს საჴსენებელი და კურთხევაჲ მისი, მრავალმცა არიან დღენი და ჟამნი ცხორებისაჲ მისისანი.", "markup": [{ "start": 234, "end": 254, "type": "persName", "ref": "p1012" }] }, "english": { "text": "And of their nephew, the valiant and heroic and eloquent, the destroyer of the Hagarenes, renowned for courage, the terror of enemies, firm holder of the faith and true law of Christ, and our present ruler, patron Nav (!) Qvarqvare, may his memory and blessing be eternal, may the days and times of his life be many." }, "prosopography": [{ "ref": "p1012", "role": "kinship" }] },
    { "id": "q969_entry_13", "manuscript": "Q-969", "n": "13", "georgian": { "text": "და მეუღლისა მათისა, ღუთივ-გჳრგჳნოსანისა (!) მთიებისა და ცისკროვნებრ ბრწყინვალისა, სიმშჳდის მეძიებელისა და წერილთ-მოყუარულისა და ჯუართა და ხატთა პირად-პირადად მამკობელისა პატრონისა ჩუენისა ანნაჲსი მრავალმცა არიან დღენი და ჟამნი ცხორებისა მისისასანი.", "markup": [{ "start": 182, "end": 188, "type": "persName", "ref": "p1013" }] }, "english": { "text": "And of his wife, the divinely-crowned luminary and brilliant like the morning star, seeker of peace and lover of letters and decorator of various crosses and icons, our patron Anna, may the days and times of her life be many." }, "prosopography": [{ "ref": "p1013", "role": "wife" }] },
    { "id": "q969_entry_14", "manuscript": "Q-969", "n": "14", "georgian": { "text": "და ძეთა მათთა, სამოთხის ნერგთა, ვარდთა სურნელთა და გონიერთა, საღმრთოდ-სამჴედროდ აღზრდილთა პატრონის მზეჭაბუკისი და პატრონის ქაიხოსროსი მრავალმცა არიან დღენი და ჟამნი ცხორებისა მათისანი.", "markup": [{ "start": 110, "end": 122, "type": "persName", "ref": "p1014" }, { "start": 136, "end": 146, "type": "persName", "ref": "p1015" }] }, "english": { "text": "And of their sons, saplings of paradise, fragrant roses and intelligent ones, raised for divine military service, the patron Mzechabuk and the patron Kaikhosro, may the days and times of their lives be many." }, "prosopography": [{ "ref": "p1014", "role": "son" }, { "ref": "p1015", "role": "son" }] },
    { "id": "q969_entry_15", "manuscript": "Q-969", "n": "15", "georgian": { "text": "და სოილ კოპას ძისა, ტავოსა ამილახორისა და მხატვრობით კეთილად ჴელოვნისა და სიბრძნის-მეტყუჱლისა და საღმრთოთა წერილთა მართლიად აღმასრულებელია და თარგმანთა განმამარტებელისა მრავალმცა არიან დღენი და ჟამნი სუფევისასა მისისანი და კუალადცა საუკუნომცა არს საჴსენებელი და კურთხევაჲ მისი.", "markup": [{ "start": 3, "end": 19, "type": "persName", "ref": "p1016" }] }, "english": { "text": "And of Soil, son of Kopa, the Tavos Amilakhori and well-skilled in painting and a speaker of wisdom and a righteous executor of divine writings and an explainer of translations, may the days and times of his reign be many, and again, may his memory and blessing be eternal." }, "prosopography": [{ "ref": "p1016", "role": "main" }] },
    { "id": "q969_entry_16", "manuscript": "Q-969", "n": "16", "georgian": { "text": "ეგრეთვე მართლმადიდებელთა და კურთხეულთა მშობელთა მისთა რუამ-ყოფილისა რაშთაელისი და რაინდო-ყოფილისა ეკატირინესი საუკუნოჲმცა არს საჴსენებელი და კურთხევაჲ მათი.", "markup": [{ "start": 57, "end": 83, "type": "persName", "ref": "p1017" }, { "start": 87, "end": 113, "type": "persName", "ref": "p1018" }] }, "english": { "text": "Likewise, of his orthodox and blessed parents, Ruam-yofili Rashtaeli and Raindo-yofili Ekaterine, may their memory and blessing be eternal." }, "prosopography": [{ "ref": "p1017", "role": "parent" }, { "ref": "p1018", "role": "parent" }] },
    { "id": "q969_entry_17", "manuscript": "Q-969", "n": "17", "georgian": { "text": "და მემცხედრისა მისისა, ღუაწლ-მრავალ და მოღუაწებით წმიდათა ქალწულთა მიმსგავსებულისა, ლოცვა-მარხვით დაუშრომელსა და სრულსა მონაზონებისა და სქემოსნობისა ღირსებით სრულქმნილსა, მანგუშარ-ყოფილსა მართასი საუკუნოჲმცა არს საჴსენებელი და კურთხევაჲ მისი.", "markup": [{ "start": 169, "end": 194, "type": "persName", "ref": "p1019" }] }, "english": { "text": "And of his female relative, of many labors and assimilated to the holy virgins through asceticism, tireless in prayer and fasting and perfected with the dignity of full monasticism and the schema, Mangushar-yofili Marta, may her memory and blessing be eternal." }, "prosopography": [{ "ref": "p1019", "role": "kinship" }] },

    // --- Entries from Q-642 ---
    { "id": "q642_entry_1", "manuscript": "Q-642", "n": "1", "georgian": { "text": "ბაგრატ აფხაზთა, ქართველთა მართლმადიდებლისა მეფისა საუკუნოჲმცა არს.", "markup": [{ "start": 0, "end": 6, "type": "persName", "ref": "p1001" }, { "start": 68, "end": 71, "type": "abbr", "expan": "არს", "abbr": "ა{რს}" }] }, "english": { "text": "Of Bagrat, orthodox king of the Abkhazians and Kartvelians, may his memory be eternal." }, "prosopography": [{ "ref": "p1001", "role": "main" }] },
    { "id": "q642_entry_2", "manuscript": "Q-642", "n": "2", "georgian": { "text": "გიორგი კესაროსისა აფხაზთა, ქართველთა მართლმადიდებლისაჲ მეფისა საუკუნოჲმცა არს.", "markup": [{ "start": 0, "end": 6, "type": "persName", "ref": "p1002" }] }, "english": { "text": "Of Giorgi the Caesar, of the Abkhazians, orthodox King of the Kartvelians, may his memory be eternal." }, "prosopography": [{ "ref": "p1002", "role": "main" }] },
    { "id": "q642_entry_3", "manuscript": "Q-642", "n": "3", "georgian": { "text": "დავით ყოვლისა აღმოსავლეთისა მეფისა ახლისა მართლისა მადიდებლობისა (!) საუკუნოჲ.", "markup": [{ "start": 0, "end": 5, "type": "persName", "ref": "p1003" }, { "start": 56, "end": 57, "type": "supplied" }, { "start": 70, "end": 79, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of Davit, king of all the East, of new true orthodoxy, may his memory be eternal." }, "prosopography": [{ "ref": "p1003", "role": "main" }] },
    { "id": "q642_entry_4", "manuscript": "Q-642", "n": "4", "georgian": { "text": "დემეტრე ყოვლისა აღმოსავლეთისა მეფისა საუკუნოჲ.", "markup": [{ "start": 0, "end": 7, "type": "persName", "ref": "p1004" }, { "start": 40, "end": 49, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of Demetre, king of all the East, may his memory be eternal." }, "prosopography": [{ "ref": "p1004", "role": "main" }] },
    { "id": "q642_entry_5", "manuscript": "Q-642", "n": "5", "georgian": { "text": "გიორგი ყოვლისა აღმოსავლეთისა ჴელმწიფედ მპყრობელისა, მეფეთ-მეფისა საუკუნოჲ-მცა.", "markup": [{ "start": 0, "end": 6, "type": "persName", "ref": "p1005" }, { "start": 71, "end": 81, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of Giorgi, ruler of all the East, King of Kings, may his memory be eternal." }, "prosopography": [{ "ref": "p1005", "role": "main" }] },
    { "id": "q642_entry_6", "manuscript": "Q-642", "n": "6", "georgian": { "text": "თამარ ყოვლისა აღმოსავლეთისა ახლისა მართლმადიდებლისა აფხაზთა, ქართველთა, ჰერთა და კახთა და ყოველთა ქრისტიანეთა მპყრობელისა საუკუნოჲ-მცა.", "markup": [{ "start": 0, "end": 5, "type": "persName", "ref": "p1006" }, { "start": 131, "end": 141, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of Tamar, new orthodox one of all the East, ruler of the Abkhazians, Kartvelians, Heretians, and Kakhetians, and all Christians, may her memory be eternal." }, "prosopography": [{ "ref": "p1006", "role": "main" }] },
    { "id": "q642_entry_7", "manuscript": "Q-642", "n": "7", "georgian": { "text": "ძისა მათისა, მეფეთ-მეფისა, ყოვლისა აღმოსავლეთისა და დასავლეთისა მტკიცედ მპყრობელისა გიორგისი საუკუნოჲ-მცაჲ არს საჴსენებელი და ...", "markup": [{ "start": 82, "end": 90, "type": "persName", "ref": "p1007" }, { "start": 82, "end": 90, "type": "supplied" }, { "start": 91, "end": 102, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უნოჲ}" }] }, "english": { "text": "Of their son, King of Kings, firm ruler of all the East and West, Giorgi, may his memory be eternal and..." }, "prosopography": [{ "ref": "p1007", "role": "kinship" }] },
    { "id": "q642_entry_8", "manuscript": "Q-642", "n": "8", "georgian": { "text": "დისა მათისა რუსუდან მართლმადიდებლისა, ყოვლისა აღმოსავლეთისა მტკიცედ მპყრობელისა საუკუნო/ჲმცა.", "markup": [{ "start": 13, "end": 20, "type": "persName", "ref": "p3001" }] }, "english": { "text": "Of their sister Rusudan, the orthodox, firm ruler of all the East, may her memory be eternal." }, "prosopography": [{ "ref": "p3001", "role": "kinship" }] },
    { "id": "q642_entry_9", "manuscript": "Q-642", "n": "9", "georgian": { "text": "დავით და დავით მართლმადიდებელთა მეფეთმეფეთა საუკუნოჲ-მცა არს.", "markup": [{ "start": 0, "end": 5, "type": "persName", "ref": "p3003" }, { "start": 0, "end": 13, "type": "supplied" }, { "start": 9, "end": 14, "type": "persName", "ref": "p3002" }, { "start": 48, "end": 57, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of David [and David], the orthodox Kings of Kings, may their memory be eternal." }, "prosopography": [{ "ref": "p3003", "role": "main" }, { "ref": "p3002", "role": "main" }] },
    { "id": "q642_entry_10", "manuscript": "Q-642", "n": "10", "georgian": { "text": "უსხეულოთა მიმსგავსებულისა წმიდისა მამისა ჩუჱნისა ეფთჳმე მთაწმიდელისა, ახლისა ოქროპირისა, ქართველთა განმანათლებელთა საუკუნოჲ.", "markup": [{ "start": 32, "end": 52, "type": "persName", "ref": "p3004" }, { "start": 40, "end": 45, "type": "abbr", "expan": "წმიდისა", "abbr": "წ{მიდ}ისა" }, { "start": 110, "end": 119, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of our holy father, likened to the bodiless ones, Euthymius the Athonite, the new Chrysostom, enlightener of the Georgians, may his memory be eternal." }, "prosopography": [{ "ref": "p3004", "role": "commemorated" }] },
    { "id": "q642_entry_11", "manuscript": "Q-642", "n": "11", "georgian": { "text": "წმიდათა და მართლმადიდებელთა დედოფალთა მარიამ და მართასი საუკუნოჲ.", "markup": [{ "start": 0, "end": 5, "type": "abbr", "expan": "წმიდათა", "abbr": "წ{მიდა}თა" }, { "start": 41, "end": 47, "type": "persName", "ref": "p3005" }, { "start": 51, "end": 57, "type": "persName", "ref": "p3006" }, { "start": 58, "end": 67, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of the holy and orthodox Queens Mariam and Martha, may their memory be eternal." }, "prosopography": [{ "ref": "p3005", "role": "commemorated" }, { "ref": "p3006", "role": "commemorated" }] },
    { "id": "q642_entry_12", "manuscript": "Q-642", "n": "12", "georgian": { "text": "წმიდათა მამათა: იოვანე და იოვანე სჳნგელოზისაჲ და გიორგისი საუკუნოჲმცა.", "markup": [{ "start": 0, "end": 5, "type": "abbr", "expan": "წმიდათა", "abbr": "წ{მიდა}თა" }, { "start": 17, "end": 23, "type": "persName", "ref": "p3007" }, { "start": 27, "end": 46, "type": "persName", "ref": "p3008" }, { "start": 50, "end": 57, "type": "persName", "ref": "p3009" }, { "start": 58, "end": 68, "type": "abbr", "expan": "საუკუნოჲმცა", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲმცა" }] }, "english": { "text": "Of the holy fathers: Iovane and Iovane the Syncellus and Giorgi, may their memory be eternal." }, "prosopography": [{ "ref": "p3007", "role": "commemorated" }, { "ref": "p3008", "role": "commemorated" }, { "ref": "p3009", "role": "commemorated" }] },
    { "id": "q642_entry_13", "manuscript": "Q-642", "n": "13", "georgian": { "text": "წმიდისა მამისა ჩუჱნისა გიორგი მთაწმიდელისა, ქართველთა მნათობისა საუკუნოჲმცა არს.", "markup": [{ "start": 0, "end": 5, "type": "abbr", "expan": "წმიდისა", "abbr": "წ{მიდ}ისა" }, { "start": 24, "end": 44, "type": "persName", "ref": "p3010" }, { "start": 69, "end": 79, "type": "abbr", "expan": "საუკუნოჲმცა", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲმცა" }] }, "english": { "text": "Of our holy father Giorgi the Athonite, enlightener of the Kartvelians, may his memory be eternal." }, "prosopography": [{ "ref": "p3010", "role": "commemorated" }] },
    { "id": "q642_entry_14", "manuscript": "Q-642", "n": "14", "georgian": { "text": "ყოველთა ნათესავთა ჩუენთა მასპინძლისა ქართველთა გრიგოლ სევასტოსისა, ბაკურიანის ძისა და ყოვლისა დასავლისა დიდისა დემესტლიკოჲსისა მართლმადიდებელისა საუკუნოჲმცა ...", "markup": [{ "start": 21, "end": 26, "type": "abbr", "expan": "ჩუენთა", "abbr": "ჩ{უე}ნთა" }, { "start": 53, "end": 90, "type": "persName", "ref": "p3011" }, { "start": 160, "end": 170, "type": "abbr", "expan": "საუკუნოჲმცა", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲმცა" }] }, "english": { "text": "Of the host of all our kin, the Georgian Grigol Sevastos, son of Bakuriani, and the orthodox Grand Domestic of all the West, may his memory be eternal..." }, "prosopography": [{ "ref": "p3011", "role": "commemorated" }] },
    { "id": "q642_entry_15", "manuscript": "Q-642", "n": "15", "georgian": { "text": "მართლმადიდებლისა მეფისა ალექსანდრესი და მეუღლისა მისისა პატრონისა დედოფალისა თამარისა საუკუნოჲ.", "markup": [{ "start": 26, "end": 37, "type": "persName", "ref": "p3013" }, { "start": 84, "end": 91, "type": "persName", "ref": "p3014" }, { "start": 92, "end": 101, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of the orthodox King Aleksandre and his wife, the patron Queen Tamar, may their memory be eternal." }, "prosopography": [{ "ref": "p3013", "role": "main" }, { "ref": "p3014", "role": "wife" }] },
    { "id": "q642_entry_16", "manuscript": "Q-642", "n": "16", "georgian": { "text": "ძისა მათისა, დიდისა მეფეთ-მეფისა ბაგრატისი და ძმათა მისთა ღმრთისმოყუარეთა გიორგი და ვახტანგისი საუკუნოჲ.", "markup": [{ "start": 33, "end": 41, "type": "persName", "ref": "p3015" }, { "start": 57, "end": 74, "type": "abbr", "expan": "ღმრთისმოყუარეთა", "abbr": "ღ{მრთ}ისმოყ[უ]არეთა" }, { "start": 75, "end": 81, "type": "persName", "ref": "p3016" }, { "start": 85, "end": 94, "type": "persName", "ref": "p3017" }, { "start": 95, "end": 104, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of their son, the great King of Kings Bagrat, and his God-loving brothers Giorgi and Vakhtang, may their memory be eternal." }, "prosopography": [{ "ref": "p3015", "role": "son" }, { "ref": "p3016", "role": "kinship" }, { "ref": "p3017", "role": "kinship" }] },
    { "id": "q642_entry_17", "manuscript": "Q-642", "n": "17", "georgian": { "text": "ღმრთისმოყუარისა, მართლმორწმუნისა პატრონისა ყუარყუარესი.", "markup": [{ "start": 0, "end": 16, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყ[უ]არისა" }, { "start": 44, "end": 56, "type": "persName", "ref": "p1012" }, { "start": 44, "end": 56, "type": "abbr", "expan": "ყუარყუარესი", "abbr": "ყ[უა]რყ[უა]რესი" }] }, "english": { "text": "Of the God-loving, orthodox patron Qvarqvare." }, "prosopography": [{ "ref": "p1012", "role": "main" }] },
    { "id": "q642_entry_18", "manuscript": "Q-642", "n": "18", "georgian": { "text": "და თანამეცხედრისაჲ მისისა პატრონისა ანასი და ძეთა მათთა პატრონისა მზეჭაბუკ და ქაიხოსროსი საუკუნოჲ.", "markup": [{ "start": 37, "end": 41, "type": "persName", "ref": "p1013" }, { "start": 69, "end": 77, "type": "persName", "ref": "p1014" }, { "start": 81, "end": 91, "type": "persName", "ref": "p1015" }, { "start": 92, "end": 101, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "And of his wife, the patron Ana, and of their sons, the patron Mzechabuk and Kaikhosro, may their memory be eternal." }, "prosopography": [{ "ref": "p1013", "role": "wife" }, { "ref": "p1014", "role": "son" }, { "ref": "p1015", "role": "son" }] },
    { "id": "q642_entry_19", "manuscript": "Q-642", "n": "19", "georgian": { "text": "ქრისტეს მოყუარისა და მართლმადიდებლისა პატრონისა სფირიდონისი და მეცხედრისა მისისა, დიდისა მეფისა ალექსანდრეს ასულისა, ღმრთისმოყუარისა, მორწმუნისა და მართლმადიდებლისა პატრონისა თინათინისი საუკუნოჲმცა.", "markup": [{ "start": 50, "end": 62, "type": "persName", "ref": "p3018" }, { "start": 50, "end": 62, "type": "supplied" }, { "start": 102, "end": 113, "type": "persName", "ref": "p3013" }, { "start": 123, "end": 139, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყუარისა" }, { "start": 178, "end": 188, "type": "persName", "ref": "p3019" }, { "start": 189, "end": 199, "type": "abbr", "expan": "საუკუნოჲმცა", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲმცა" }] }, "english": { "text": "Of the Christ-loving and orthodox patron Spiridon, and of his wife, daughter of the great King Aleksandre, the God-loving, faithful and orthodox patron Tinatin, may their memory be eternal." }, "prosopography": [{ "ref": "p3018", "role": "main" }, { "ref": "p3013", "role": "kinship" }, { "ref": "p3019", "role": "wife" }] },
    { "id": "q642_entry_20", "manuscript": "Q-642", "n": "20", "georgian": { "text": "ძისა მათისა, ღმრთისმოყუარისა და მართლმორწმუნისა პატრონისა იოსაფატისი და მეცხედრისა მისისა მართლმორწმუნისა და ღმრთისმოყუარისა პატრონისა ქეთაონისი მრავალმცა არიან წელნი ცხორებისა მათისნი და საუკუნომცა ჴსენებაჲ და კურთხევაჲ მათი. და ძეთა მათთა მრავალმცა არიან წელნი ცხორებისა მათისა და საუკუნოჲ ჴსენებაჲ და კურთხევაჲ.", "markup": [{ "start": 14, "end": 30, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყუარისა" }, { "start": 62, "end": 72, "type": "persName", "ref": "p3020" }, { "start": 120, "end": 136, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყუარისა" }, { "start": 149, "end": 157, "type": "persName", "ref": "p3021" }, { "start": 272, "end": 281, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }, { "start": 293, "end": 302, "type": "abbr", "expan": "კურთხევაჲ", "abbr": "კ{ურთ}ხ{ევაჲ}" }] }, "english": { "text": "Of their son, the God-loving and orthodox patron Iosapat, and of his wife, the orthodox and God-loving patron Ketaon, may the years of their life be many, and may their memory and blessing be eternal. And for their sons, may the years of their lives be many, and their memory and blessing be eternal." }, "prosopography": [{ "ref": "p3020", "role": "son" }, { "ref": "p3021", "role": "wife" }] },
    { "id": "q642_entry_21", "manuscript": "Q-642", "n": "21", "georgian": { "text": "ღმრთისმოყუარისა პატრონისა მამისასი და ქრისტეს მოყუარისა პატრონისა ირინესი და მართლმორწმუნისა პატრონისა აბდულმისესი საუკუნოჲმცა.", "markup": [{ "start": 0, "end": 16, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყუარისა" }, { "start": 29, "end": 36, "type": "persName", "ref": "p3022" }, { "start": 66, "end": 72, "type": "persName", "ref": "p3023" }, { "start": 100, "end": 111, "type": "persName", "ref": "p3024" }, { "start": 112, "end": 122, "type": "abbr", "expan": "საუკუნოჲმცა", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲმცა" }] }, "english": { "text": "Of the God-loving patron Mamisa and the Christ-loving patron Irine and the orthodox patron Abdulmese, may their memory be eternal." }, "prosopography": [{ "ref": "p3022", "role": "commemorated" }, { "ref": "p3023", "role": "commemorated" }, { "ref": "p3024", "role": "commemorated" }] },
    { "id": "q642_entry_22", "manuscript": "Q-642", "n": "22", "georgian": { "text": "ღმრთისმოყუარისა და მართლმორწმუნისა პატრონისა ელენისი საუკუნოჲმცა.", "markup": [{ "start": 0, "end": 16, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყუარისა" }, { "start": 37, "end": 39, "type": "supplied" }, { "start": 51, "end": 57, "type": "persName", "ref": "p3025" }, { "start": 58, "end": 68, "type": "abbr", "expan": "საუკუნოჲმცა", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲმცა" }] }, "english": { "text": "Of the God-loving and orthodox patron Elene, may her memory be eternal." }, "prosopography": [{ "ref": "p3025", "role": "commemorated" }] },
    { "id": "q642_entry_23", "manuscript": "Q-642", "n": "23", "georgian": { "text": "ძისა მათისა ღმრთისმოყუარისა პატრონისა იორამისი საუკუნოჲ.", "markup": [{ "start": 13, "end": 29, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყუარისა" }, { "start": 42, "end": 49, "type": "persName", "ref": "p3026" }, { "start": 50, "end": 59, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of their son, the God-loving patron Ioram, may his memory be eternal." }, "prosopography": [{ "ref": "p3026", "role": "kinship" }] },
    { "id": "q642_entry_24", "manuscript": "Q-642", "n": "24", "georgian": { "text": "ღმრთისმოყუარისა მართლმორწმუნისა პატრონისა თამარისა საუკუნოჲ.", "markup": [{ "start": 0, "end": 16, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყუარისა" }, { "start": 44, "end": 51, "type": "persName", "ref": "p3027" }, { "start": 52, "end": 61, "type": "abbr", "expan": "საუკუნოჲ", "abbr": "ს{აუ}კ{უ}ნ{ო}ჲ" }] }, "english": { "text": "Of the God-loving orthodox patron Tamar, may her memory be eternal." }, "prosopography": [{ "ref": "p3027", "role": "commemorated" }] },
    { "id": "q642_entry_25", "manuscript": "Q-642", "n": "25", "georgian": { "text": "ღმრთისმოყუარისა და მართლმორწმუნისა პატრონისა გულქანისი მრავალმცა არიან წელნი ცხორებისა მისისანი და საუკუნოჲმცა არს ჴსენებაჲ და კურთხევაჲ მისი და ძეთა მისთა მრავალმცა არიან წელნი ცხორებისა მისისანი.", "markup": [{ "start": 0, "end": 16, "type": "abbr", "expan": "ღმრთისმოყუარისა", "abbr": "ღ{მრ}თისმოყუარისა" }, { "start": 44, "end": 52, "type": "persName", "ref": "p3028" }, { "start": 105, "end": 114, "type": "abbr", "expan": "კურთხევაჲ", "abbr": "კ{ურთ}ხ{ე}ვაჲ" }] }, "english": { "text": "Of the God-loving and orthodox patron Gulkan, may the years of her life be many, and may her memory and blessing be eternal, and for her sons, may the years of their lives be many." }, "prosopography": [{ "ref": "p3028", "role": "commemorated" }] }
  ]
};
